linters:
  enable-all: true
  disable:
      - funlen # TODO(ppacher): re-enable ASAP
      - gomnd # we do have a lot of "magic-numbers" in our V() loggers

linters-settings:
  godox:
    # report any comments starting with keywords, this is useful for TODO or FIXME comments that
    # might be left in the code accidentally and should be resolved before merging
    keywords:
      - FIXME
      - NOCOMMIT
