version: '3.1'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-import:
    image: mongo
    depends_on:
      - mongo
    restart: on-failure
    volumes:
      - ../:/project
    command: bash /project/deploy/import-data.sh

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

#  dxray:
#    image: tkd/dxray
#    build: https://github.com/tierklinik-dobersberg/dxray.git
#    ports:
#      - 9100:9100
#    volumes:
#      - ./dxray.conf:/config/dxray.conf
#      - ../testdata/dxray:/mnt
#    environment:
#      CONFIGURATION_DIRECTORY: /config

  cisd: 
    image: tkd/cisd
    build: ../
    depends_on:
      mongo:
        condition: service_started
      mosquitto:
        condition: service_started
      mongo-import:
        condition: service_completed_successfully
    ports:
      - 3000:3000
    volumes:
      - ../:/project
      - /home/ppc/mnt/Infdat:/mnt
      - /tmp/cislog:/log
    environment:
      CONFIGURATION_DIRECTORY: /project/testdata/config
      STATE_DIRECTORY: /project/testdata/state
      TZ: ""
