version: '3.1'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-import:
    image: mongo
    depends_on:
      - mongo
    restart: on-failure
    volumes:
      - ../:/project
    command: bash /project/deploy/import-data.sh

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  #
  # We use radicale as our upstream CardDAV server.
  #
  radicale:
    image: tomsquest/docker-radicale:latest
    ports:
      - 8091:8091
    volumes:
      - ../testdata/state/radicale:/data
      - ./radicale.conf:/config/config:ro
      - ./radicale.users:/config/users:ro

  #
  # Import a collection for the admin user.
  #
  radicale-init:
    image: curlimages/curl:latest
    depends_on:
      radicale:
          condition: service_started
    volumes:
      - ../testdata/dump/carddav-collection.vcf:/tmp/addressbook.vcf
    command:
      - 'http://admin:password@radicale:8091/admin/2876ee8f-c693-8a49-bf95-25d41c97b674/' 
      - -XPUT
      - '-HContent-Type: text/vcard'
      - --data-binary
      - '@/tmp/addressbook.vcf'

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

#  dxray:
#    image: tkd/dxray
#    build: https://github.com/tierklinik-dobersberg/dxray.git
#    ports:
#      - 9100:9100
#    volumes:
#      - ./dxray.conf:/config/dxray.conf
#      - ../testdata/dxray:/mnt
#    environment:
#      CONFIGURATION_DIRECTORY: /config

  cisd: 
    image: tkd/cisd
    build: ../
    depends_on:
      mongo:
        condition: service_started
      mosquitto:
        condition: service_started
      mongo-import:
        condition: service_completed_successfully
      radicale-init:
        condition: service_completed_successfully
    ports:
      - 3000:3000
    volumes:
      - ../:/project
      - /home/ppc/mnt/Infdat:/mnt
      - /tmp/cislog:/log
    environment:
      CONFIGURATION_DIRECTORY: /project/testdata/config
      STATE_DIRECTORY: /project/testdata/state
      TZ: ""

  uidev:
    image: node:latest
    user: 1000:1000
    ports:
      - 4200:4200
    volumes:
      - ../ui:/project
    environment:
      TZ: ""
    working_dir: /project
    command: bash -c "npm install && ./node_modules/.bin/ng serve --configuration=compose --host=0.0.0.0 --port=4200 --proxy-config ./proxy.deploy.json"
    
