version: "3.1"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.30
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-import:
    image: mongo
    depends_on:
      - mongo
    restart: on-failure
    volumes:
      - ../:/project
    command: bash /project/deploy/import-data.sh

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  #
  # Fake SMTP server to test mail delivery
  #
  smtp:
    image: reachfive/fake-smtp-server
    ports:
      - 8092:1080
    command: node index.js --auth mailuser:mailpass

  #
  # We use radicale as our upstream CardDAV server.
  #
  radicale:
    image: tomsquest/docker-radicale:latest
    ports:
      - 8091:8091
    volumes:
      - ../testdata/state/radicale:/data
      - ./radicale.conf:/config/config:ro
      - ./radicale.users:/config/users:ro

  #
  # Import a collection for the admin user.
  #
  radicale-init:
    image: curlimages/curl:latest
    depends_on:
      radicale:
        condition: service_started
    volumes:
      - ../testdata/dump/carddav-collection.vcf:/tmp/addressbook.vcf
    command:
      - "http://admin:password@radicale:8091/admin/2876ee8f-c693-8a49-bf95-25d41c97b674/"
      - -XPUT
      - "-HContent-Type: text/vcard"
      - --data-binary
      - "@/tmp/addressbook.vcf"

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  #  dxray:
  #    image: tkd/dxray
  #    build: https://github.com/tierklinik-dobersberg/dxray.git
  #    ports:
  #      - 9100:9100
  #    volumes:
  #      - ./dxray.conf:/config/dxray.conf
  #      - ../testdata/dxray:/mnt
  #    environment:
  #      CONFIGURATION_DIRECTORY: /config

  cisd:
    image: tkd/cisd
    build: 
      context: ../
      dockerfile: ./Dockerfile
      #dockerfile: ./Dockerfile.debug
    depends_on:
      mongo:
        condition: service_started
      mosquitto:
        condition: service_started
      mongo-import:
        condition: service_completed_successfully
      radicale-init:
        condition: service_completed_successfully
    ports:
      - 3000:3000
      - 40000:40000
    volumes:
      - ../:/project
      - /home/ppc/mnt/Infdat:/mnt
      - /tmp/cislog:/log
    environment:
      CIS_BOOTSTRAP_ADMIN: "password"
      CIS_IMPORT_VETINFIMPORTDISABLED: "yes"
      CONFIGURATION_DIRECTORY: /project/testdata/config
      STATE_DIRECTORY: /project/testdata/state
      TZ: ""

  uidev:
    image: node:16
    user: 1000:1000
    ports:
      - 4200:4200
    volumes:
      - ../ui:/project
    environment:
      TZ: ""
    working_dir: /project
    command: bash -c "npm install && ./node_modules/.bin/ng serve --configuration=compose --host=0.0.0.0 --port=4200 --proxy-config ./proxy.deploy.json"
