name: integration-tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: apt-get update && apt-get install -y libssh-4
      - run: pip3 install docker-compose --upgrade
      - name: Run integration tests
        run: cd integration && go test -v -count=1 . -build=true -log=cisd
