name: integration-tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Building cisd
        run: cd integration && docker-compose build cisd
      - name: Run integration tests
        run: cd integration && go test -v -count=1 . -build=false
      - name: Setup environment
        run: cd integratoin && docker-compose up -d
      - name: Run Jasmine tests
        run: cd spec && npm install && npm test
      - name: Teardown environment
        run: cd integration && docker-compose down