name: integration-tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Building cisd
        run: cd deploy && docker-compose build cisd
      - name: Setup environment
        run: cd deploy && docker-compose up -d
      - name: Run Jasmine tests
        run: cd spec && npm install && CI=true npm test || ( cd ../deploy ; docker-compose logs cisd ; exit -1 )
      - name: Teardown environment
        run: cd deploy && docker-compose down